### ISSUE TITLE
Buy/Implement SSL certificate

### ISSUE THREAD

**Issue by adis-me** [jvandenaardweg/coinaly#22]
Of course we need SSL for our domain after #2 has resolved. After installing SSL we need to get the highest available score. I often use https://www.ssllabs.com/ssltest/ for this purpose.

I'm not sure if the Google Lighthouse will extensively test our SSL config, if so this issue will be resolved in #21

**Comment by jvandenaardweg** [comment]
Score: A

https://www.ssllabs.com/ssltest/analyze.html?d=coinaly.io&hideResults=on&latest
