### ISSUE TITLE
Highlight worth on balance when it increases green or decrease red

### ISSUE THREAD

**Issue by adis-me** [jvandenaardweg/coinaly#31]
On the **/balances** page and **/** we should highlight the amounts when they change. Coinlib does the same thing, I personally like it.

- [x] when a currency increases in worth: highlighted in `#269f42`
- [x] when a currency decreases in worth: highlight in `#ef1227`

WDYT?

**Comment by jvandenaardweg** [comment]
I've just added this feature to the website, including total balance worth on top of the balance page. Was pretty easy to do, so moved it to v1.0 :)
