### ISSUE TITLE
Show a notice when Bitcoin is having a run

### ISSUE THREAD

**Issue by jvandenaardweg** [jvandenaardweg/coinaly#35]
Lately (i’m not that long in the crypto trade world) i notice when BTC/USD rises with more than 5-10%, 99% of the altcoins seem to suffer and instantly go down.

I think its useful to show a site wide notice when bitcoin is running up, so you kinda know why your altcoins are performing bad
  
Would love to know if others might find this useful

**Comment by adis-me** [comment]
Would like these kind of notifications. But is there a general rule on the time restriction that can be defined? 5% change in 1 minute, or 1 hour?

**Comment by jvandenaardweg** [comment]
Totally depends on what the method is too determine that jump. On Bittrex i noticed the change percentage is already around 5% (up) when the other coins go down. Think we’ll have to do a little more digging in what drives the shift if we want the be 100% correct

**Comment by jvandenaardweg** [comment]
Deploying!

Will show a orange warning when BTC's dips below 4%
Will show a red warning when BTC dips below 20%

<img width="440" alt="screenshot 2018-01-16 23 22 33" src="https://user-images.githubusercontent.com/5155373/35015322-2bb12726-fb14-11e7-9048-e9a9570b5e1c.png">
