### ISSUE TITLE
Namechange to Coinaly and made repo public

### ISSUE THREAD

**Issue by jvandenaardweg** [jvandenaardweg/coinaly#36]
The previous name "Simpletrade" was just a name to get the project started. Now we changed to "Coinaly". 

It's really hard to find a suitable name for a project these days, but i think Coinaly fits this one.

The `coin` party is really obvious; this is a trade interface for cryptocurrencies (aka coins)
The `aly` part references to "analyzing" and "easy". Since trading is part analyzing. And the platform must be easy to use.

Also, saying "Coinaly" sounds pretty good. So, this is the name we are going to use :-)

Coinaly.io is already bought.

I'm currently in the process of changing all the references.

Alpha website will be: https://coinaly.io (can take 24hrs for it to be available)
Repo will be: https://github.com/jvandenaardweg/coinaly
Slack: [coinaly.slack.com](https://coinaly.slack.com) > [direct invite link](https://join.slack.com/t/coinaly/shared_invite/enQtMjk1OTcxMTc2MTE4LWJjMzJkOTg2ODY4MzI4MzRiNmMxNmRlODY1OWZjNjA0MGVlOWFkNGJiNjMyYjNhNzRjMjY4YmI2MzI5MTFiMzg)

The reason I made this repository public is to allow other dev's to join in on this.

**Comment by adis-me** [comment]
Can you check why SSL still fails. On Chrome I see the following error:

```
coinaly.io uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by jvandenaardweg** [comment]
Cloudflare is still in the process of setting up the DNS and nameservers. Could take another few hours

**Comment by jvandenaardweg** [comment]
HTTPS is working now. Will also order a SSL cert specific for this domain. Its now using a free cloudflare one

**Comment by jvandenaardweg** [comment]
All set. Fully https now

**Comment by jvandenaardweg** [comment]
SSL rating is A+ now: https://www.ssllabs.com/ssltest/analyze.html?d=coinaly.io&hideResults=on&latest
