### ISSUE TITLE
Create seperate Heroku services

### ISSUE THREAD

**Issue by jvandenaardweg** [jvandenaardweg/coinaly#38]
In order to use websockets (https://github.com/jvandenaardweg/coinaly/issues/8) we need to seperate processes on Heroku

**1. web**
the front-facing website (Node, VueJS)

**2. api**
server that returns exchange API data (Node, Express)

**3. socket**
server that returns exchange socket data (ticker information) (Node, Websocket)

Heroku does not support multiple "web" processes in 1 Procfile. So I came accross this:
https://github.com/heroku/heroku-buildpack-multi-procfile

This issue is to seperate those 3 processes by the use of that Heroku buildpack.

So we end up with:
https://coinaly.io (web)
https://api.coinaly.io (api)
https://socket.coinaly.io (socket)

**Comment by adis-me** [comment]
Will these projects become separate repo's or just processes on Heroku?

**Comment by jvandenaardweg** [comment]
With that build-pack it's possible to keep just one repo :)

**Comment by jvandenaardweg** [comment]
Done!

When you visit the website you probably get an error that your API key and secret is invalid. This is because of the new API domain. The message is a little bit wrong on this.

Just enter your API and secret again and you are good to go.
