### ISSUE TITLE
Cancel a SELL order: nothing happens

### ISSUE THREAD

**Issue by adis-me** [jvandenaardweg/coinaly#45]
## Expected Behavior
When _Cancelling a SELL order_ I except the the sell order is cancelled and the screen refreshes to show the outstanding _(pending)_ sell orders.

## Actual Behavior
I get a confirmation dialog but when I click on **OK** nothing happens (visually).

## Steps to Reproduce the Problem (assuming you have pending SELL order)

  1. Go to **Orders** on [coinaly.io](https://coinaly.io)
  1. Expand one of your sell orders and click on **Cancel**
  1. Notice that nothing is happening

## Specifications

  - OS: macOS High Sierra 10.13.2
  - Browser: Google Chrome 63.0.3239.132

## Console errors:
Only messages I see in the console are:

```
created homepage
created orderspage
```
On the network tab I see these 2 requests:

![screen shot 2018-01-17 at 11 18 42](https://user-images.githubusercontent.com/1314455/35037595-44188d4a-fb78-11e7-8d68-95fd4430c834.png)

**Note** on the highlighted request there is no response body? Perhaps by design?

I you do not have time I will try to investigate this issue further or even fix it :-)

**Comment by jvandenaardweg** [comment]
Hmm strange. What status number you got from the response? 200?

**Comment by adis-me** [comment]
> Hmm strange. What status number you got from the response? 200?

Yes, status 200.  That is also visible in the printscreen that I provided, on the upper left part are the key values from the _Response Headers_ visible.

**Comment by jvandenaardweg** [comment]
I've looked into it. I tried it out with an open order of mine. 

After cancelling we get a proper response from Bittrex confirming the order is cancelled. After that, we call the API again to get the open orders. I noticed my order was still in there. After a refresh the orders API does not return it anymore.

Seems like a Bittrexx caching thing.

This is the code used:

```
// Cancel the order
this.$store.dispatch('orders/cancelOrder', uuid)
.then(response => {
  // Get the balance and order history after placing the order
  // so everything is up-to-date again
  this.$store.dispatch('balances/getAll')
  this.$store.dispatch('orders/getAllHistory')

  // Finally get the open orders
  this.$store.dispatch('orders/getOpenOrders')
  .finally(() => {
    this.isLoading = false
  })
})
```

As you can see, we get the open orders again after we get a success from the cancelorder.

Maybe it's a good idea to interval through the openorders endpoint untill the order is really removed from the response.

**Comment by adis-me** [comment]
> After cancelling we get a proper response from Bittrex confirming the order is cancelled. After that, we call the API again to get the open orders. I noticed my order was still in there. After a refresh the orders API does not return it anymore. Is this what you also noticed? Or does your order still exists after a page refresh?

My sell order is still in there, even after a page refresh. I assume something is wrong at Bittrex then. I will log into Bittrex to see why it cannot be cancelled...

I saw your temporary fix. Some other thoughts/approaches that can be reviewed at a later stage:
- mark them `Cancelled`, there is even a property on the every order called: `CancelInitiated`. Then somehow ping for response until it's deleted?

**Comment by adis-me** [comment]
My behaviour was actually as expected: I did not activated **Trade market** for my API key and therefore Bittrex did not take any action when I cancelled from Coinaly.io. Enabling Trade market is mentioned in the README.md though.

**Comment by jvandenaardweg** [comment]
Ah good find about the cancelling. That makes sense now. Maybe good idea to update the issue template with a check for API permissions, so we can spot these things faster in the future!

About the cache; well, thats my guess. The first order history response i get back right after cancelling (so we talk in milliseconds) still had the order in it, so it seems cached in some way. Can debug it further to check if it’s CloudFlare..

**Comment by jvandenaardweg** [comment]
I'll close this one for now. Feel free to re-open is issue is still there.
